---
title: "The Black Keys and Their Spotify Metadata"
author: 
  - Liam Wall
thanks: "Code and data are available at: https://github.com/Lwall02/Spotify"
date: 10 October 2024
date-format: long
format: pdf
number-sections: true
bibliography: references.bib
---

```{r}
#| include: false
#| warning: false
#| message: false

library(tidyverse)
library(ggplot2)

# This data is not necessarily reporoducible because I retrieve the data using the Spotify API and a personal client ID
# black_keys_clean <- readRDS("/Users/liamwall/Spotify/data/black_keys_cleaned.rds")
```

# Introduction
This short paper will not be a rundown of the history of a band, or the story of their making, or reason they are so successful. This will be a paper about a band I really, some of the facts I know about them, the reason they are so appealiing to me, and some of the explanations I give to the trends I observe in the data I have. The band in question is The Black Keys. To start, The Black Keys are a rock band from Akron, Ohio with singer/guitarist Dan Auerbach and drummer Patrick Carney. The band itself started as just a duo of good friends who enjoyed similar music. Their first album, The Big Come Up was released in 2002, the year I was born. Their second album, released in 2003, named Thickfreakness, is where my appreciation for the band began. 

Starting with Thickfeakness, The Black Keys could be considered a garage rock band. Raw sounds from a distorted guitar and a solo drummer drew me in. They adopt a blues sound which I really enjoy and is very present in their second to fifth albums. In particular they draw inspiration from Mississippi Hill Country Blues. A genre of blues that comes from none other than the Mississippi hill country by artists like Junior Kimbrough and R.L. Burnside. Before getting into their influence on The Black Keys, the Mississippi hill country blues was popularized by Junior Kimbrough's rural juke joint. It was a small juke joint (or bar/restaurant) in Chulahoma, Mississippi, where this sound made its way to greater public. The sound was so attractive to musicians and fans alike that even famous names like Keith Richards, The Edge from U2, and Iggy Pop would come out to hear and even join in with the bands that were playing and showcasing this unique blues music. 

Dan Auerbach and Pat Carney enjoyed the music of the Mississippi hill country in their early days and their chemistry as artists began by jamming to songs from Junior Kimbrough and R.L. Burnside. Their third album, Rubber Factory, is a display of their passion for the hill country blues mixed with the innovative sound they developed ontheir own. None of the songs are covers, but the lyrics emmenate the hill country genre while the sound is a more upbeat and cleaner take on the genre. A interesting fact I like about this album is the name Rubber Factory came from the studio they recorded the album in - a decommisioned tire factory in their hometown of Akron, Ohio. 

Their fourth album, one of my favorites, is called Chulahoma. As mentioned before, Chulahoma is a town in Missippippi where Junior Kimbrough would play and the album is a tribute to Junior after his death. This album is very unique for The Black Keys because the songs are covers of Junior's songs with the influence of Dan and Pat's sound. They are longer songs with soulful lyrics and sounds from the guitar that mencompass what the blues used to be. The songs would convey just as much emotion without lyrics as they do with. The album even features a recorded voice mail from Junior's wife complimenting The Black Keys take on his music. 

Their later albums, Attack and Release to present, showcase a different side of The Black Keys. A side where they start making money and have the ability to introduce a lot more production and extra musicians to bring their vision to life. They include other instruments like piano, electronic sounds, and more upbeat "poppy" sounds. Their albums Brothers and El Camino respectively released in 2010 and 2011 are particularly large hits. It hit me one day when I was in middle school just how popular they were when I saw them playing live at an NBA game. Some of their most popular songs ever are from these albums like "Gold on the Celing," "Lonely Boy" and "Howlin For You." 

# Data
I have rambled so now we will explore the data quickly. The data was retrieved using Spotify's API on the open source programming language R [@cite-R][@cite-spotifyr]. The available data regarding The Black Keys is a table with 222 observations over 39 variables. The observations are for each song in their discography and the variables range from links, previews of the songs, images of the albums, album name, song name and duration, to variables that examine features of the audio [@cite-black-keys-data]. The features of the audio that Spotify gives us are things like a measure of bpm, key, happiness (valence), loudness, likelihood of being live, acousticness, and 'speechiness.' Spotify has a well formed way of attaining these values that can be explored at https://developer.spotify.com/documentation/web-api/reference/get-audio-features#. 


